name: Build Results

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
        
jobs: 
  build-results:
    permissions:
      pull-requests: write # Required for writing comments to the pull request

    runs-on: ubuntu-latest

    steps:
      - name: Restore Test Results
        id: download-test-results
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: pull_requests.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: test-results
      - name: Restore PR Details
        continue-on-error: true
        id: download-pr-number
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: pull_requests.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: pr-number
      - name: Read the pr file
        if: success()
        id: pr-read
        uses: juliangruber/read-file-action@v1.0.0
        with:
          path: ./pr.txt
      - name: Add Coverage PR Comment
        if: success()
        uses: marocchino/sticky-pull-request-comment@v2
#        if: ${{ github.event.workflow_run.workflow.event_name == 'pull_request' }}
        with:
          # When re-run, hide existing comments and creates a new one
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          path: code-coverage-results.md
          number: ${{steps.pr-read.outputs.content}}